### ISSUE TITLE
Feature: hyphenized keywords

### ISSUE THREAD

**Issue by katox** [layerware/hugsql#40] opened 2016-05-24 14:27 UTC
It's a bit awkward to use keywords with underscores when the rest of the application uses hyphens. It would be useful if hugsql could convert underscores in keywords (in and out) automatically without an additional wrapper.

**Comment by csummers** [comment] 2016-05-24 14:49
This is a duplicate of #21, which has details on how you can use HugSQL's return flag hooks to implement case-converting and hyphen/dash-converting versions for query results.

You could likewise do the same for incoming parameter types, but you can already use hyphenated keywords within your SQL:  `select * from test where id = :my-hyphenated-id`

**Comment by csummers** [comment] 2016-05-24 15:13
I'm still not totally opposed to adding some kind of option that would allow users to define this behavior when calling `def-db-fns`.  Your additional request adds some support for that eventually happening.

**Comment by katox** [comment] 2016-05-24 21:17
Thanks for hint to `result-fn,` I didn't get it from the docs. 

Maybe some kind of transformation middleware would be good for this. With **clojure.spec** around the corner there should be a bump in popularity of namespaced keywords too.

Not quite sure how to access information bits from a query but something like
```
    "select building.*, site.name from building, site where building.site_id = site.id"
    ==> { :building/id 1
          :building/name "tower"
          :building/long-name "City Tower"
          :site/name "Big City" }
```
would be really useful.

**Comment by arichiardi** [comment] 2016-05-27 23:29
I :+1: to this, especially the pluggable middleware would make HugSql even more powerful than it is now.
I call `(cske/transform-keys csk/->kebab-case ...)` after each query call and at the moment it is not easy to hook it up automatically being vars interned by a macro.
I was thinking of using [robert-hooke](https://github.com/technomancy/robert-hooke) for automating the process...

**Comment by LukasRychtecky** [comment] 2018-07-18 08:40
HJi @katox you can create an adapter for this. And I did it see https://github.com/druids/hugsql-adapter-case

**Closed** 2019-03-01 20:01 UTC
Labels: duplicate
