### ISSUE TITLE
How to make interval queries work?

### ISSUE THREAD

**Issue by kanwei** [layerware/hugsql#35] opened 2016-03-25 15:20 UTC
Trying to do this in postgres:

``` and timestamp > now() - interval :recent days ```

What I want it to look at the end is:

``` and timestamp > now() - interval '10' days ```

But plugging :recent as a string doesn't work... returns org.postgresql.util.PSQLException: ERROR: syntax error at or near "$2" Position: 240

**Comment by csummers** [comment] 2016-03-25 20:05
I don't see anything immediately suspect here.  Can you look at your postgresql log for hints?  Are you sure that the error is from the interval?  If so, what does the resulting query look like in your postgresql log?

**Comment by csummers** [comment] 2016-03-25 20:47
So, I'm not exactly sure why the above doesn't work, but I confirmed that it does not.

I think it has to do with what Postgresql considers an interval data type and what the JDBC driver is ok with.  You can get it to work by casting a string like so:

``` clj
(hugsql/db-run db "select now() - :recent::interval as test" {:recent "10 days"})
;=> ({:test #inst "2016-03-15T20:42:29.773498000-00:00"})
```

(You will need to be on HugSQL 0.4.5 to use this pg cast syntax as a suffix on the HugSQL parameter, since 0.4.5 added support for this case.)

**Comment by csummers** [comment] 2016-03-25 20:54
Yes, so this looks to be related to Postgresql's JDBC.  See [this StackOverflow post](http://stackoverflow.com/questions/24998959/how-to-set-5-day-datetime-interval-in-jdbc-for-postgresql) that has a few other suggestions.  For instance, if you are only working in days, you can put a 1 day interval in the query and then pass in a day multiplier as an integer.

**Comment by csummers** [comment] 2016-03-28 13:02
@kanwei Did the solution provided above work for you?

**Comment by csummers** [comment] 2016-03-29 10:57
Closing this, but feel free to re-open if the above solution with casting doesn't work out.

**Closed by csummers** 2016-03-29 10:57 UTC

**Comment by kanwei** [comment] 2016-03-29 17:29
The '1 days' * n worked, but not the :recent::interval (still same error and I tried it before). Are you sure the latter works for you?

**Comment by csummers** [comment] 2016-03-29 18:21
Yes, the example above was a run on Postgresql.  Did you pass in "10 days" as the parameter?

**Comment by lukaszkorecki** [comment] 2020-01-17 22:39
I'm running into this issue as well - I've created a small test repo:

https://github.com/lukaszkorecki/hugsql-bug/

The relevant queries are here:  

https://github.com/lukaszkorecki/hugsql-bug/blob/d91bcd95e1d1ceb4af680e9ae4d37744b32efad3/src/hugsql_interval_bug/test.sql#L19-L24

And here's a small test case:

https://github.com/lukaszkorecki/hugsql-bug/blob/d91bcd95e1d1ceb4af680e9ae4d37744b32efad3/test/hugsql_interval_bug/core_test.clj#L17-L28

The resulting error is: 

```
ERROR in (a-test) (QueryExecutorImpl.java:2505)
expected: (= 3 (core/find-widgets-broken conn {:added-since "1 day"}))
  actual: org.postgresql.util.PSQLException: ERROR: syntax error at or near "$1"
  Position: 72
 at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse (QueryExecutorImpl.java:2505)
    org.postgresql.core.v3.QueryExecutorImpl.processResults (QueryExecutorImpl.java:2241)
    org.postgresql.core.v3.QueryExecutorImpl.execute (QueryExecutorImpl.java:310)
    org.postgresql.jdbc.PgStatement.executeInternal (PgStatement.java:447)
    org.postgresql.jdbc.PgStatement.execute (PgStatement.java:368)
    org.postgresql.jdbc.PgPreparedStatement.executeWithFlags (PgPreparedStatement.java:158)
    org.postgresql.jdbc.PgPreparedStatement.execute (PgPreparedStatement.java:147)
    com.zaxxer.hikari.pool.ProxyPreparedStatement.execute (ProxyPreparedStatement.java:44)
    com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute (HikariProxyPreparedStatement.java:-1)
    next.jdbc.result_set$stmt__GT_result_set.invokeStatic (result_set.clj:509)
    next.jdbc.result_set$stmt__GT_result_set.invoke (result_set.clj:504)
    next.jdbc.result_set$eval1575$fn__1583.invoke (result_set.clj:628)
    next.jdbc.protocols$eval1003$fn__1034$G__994__1043.invoke (protocols.clj:33)
    next.jdbc.result_set$eval1611$fn__1616.invoke (result_set.clj:688)
    next.jdbc.protocols$eval1003$fn__1034$G__994__1043.invoke (protocols.clj:33)
    next.jdbc$execute_BANG_.invokeStatic (jdbc.clj:202)
    next.jdbc$execute_BANG_.invoke (jdbc.clj:189)
    hugsql.adapter.next_jdbc.HugsqlAdapterNextJdbc.query (next_jdbc.clj:20)

```

**Comment by csummers** [comment] 2020-01-18 14:35
@lukaszkorecki Thanks for the detailed report.  In this instance, you don't need the `interval` before the parameter.  The idea is that you are casting a string to an interval with the `::interval`, so the `interval` before the string is not needed:

```
diff --git a/src/hugsql_interval_bug/test.sql b/src/hugsql_interval_bug/test.sql
index 6ea0ee5..0ddd830 100644
--- a/src/hugsql_interval_bug/test.sql
+++ b/src/hugsql_interval_bug/test.sql
@@ -21,4 +21,4 @@ select * from widgets where created_at >= current_timestamp - interval '1 day';
 
 -- :name find-widgets-broken :?
 
-select * from widgets where created_at >= current_timestamp - interval :added-since::interval
+select * from widgets where created_at >= current_timestamp - :added-since::interval
```

**Comment by lukaszkorecki** [comment] 2020-01-18 18:05
@csummers got it now, thanks 👍 if that makes sense I can make a PR in the documentation to clarify the behavior, it wasn't that obvious (to me) when I read the part about casting passed in parameters.

**Comment by csummers** [comment] 2020-01-18 18:48
Glad you got it working.  

This ends up being an edge case because the syntax for an interval in SQL is strange, but the way to think about it is to realize that Postgresql treats an `interval` as a data type.  So, the easy work-around in HugSQL is to pass in a string and then cast it.  However, you could also create an instance of the `PGInterval` object from the JDBC driver and pass it in as a normal HugSQL value parameter.  (See https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/util/PGInterval.html)
